// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://obmbixnqwecxtkdxffsg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ibWJpeG5xd2VjeHRrZHhmZnNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5MTA4MzUsImV4cCI6MjA3MzQ4NjgzNX0.zBTnK7rDYwOeIZVEhnqts5uuVN6pBCwYlmcQxd31DTI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});